---

title: SPD Project Review Template 
 date: "`r file.mtime(knitr::current_input())`"
 #bibliography: ../media/references.bib
 output: 
   html_document:
     toc_depth: 3
     number_sections: true
 ---

 # Overview

 Title of project: Mortality due to positive COVID-19 Cases and its relatioship with Pneumonia and Influenza

 Name of project author(s): Alexandra Gil

 Name of project reviewer: Sophia Drewry


 # Instructions
 Write your comments and feedback below for each section/component of the project. The goal should be to help the author improve their project. Make comments as constructive and actionable as possible. You can provide both criticism and praise.

 For each component, pick one summary statement by deleting the ones that do not apply and keeping only the one that you think most closely summarizes a given component. 

 Make sure your final document compiles/knits into a readable, well-formatted html document.

 Delete any sections/text of this template that are not part of your final review document. (Including these instructions.)


 # Specific project content evaluation
 ## Background, Context and Motivation
 How well is the context of the project described? Is a comprehensive background, including summary of previous/related work given? Is the project well placed into the context of existing work (including proper referencing of existing work). Is it clear why the project was undertaken and what new information it hopes to provide?
 ### Feedback and Comments
 I checked out the Manuscript.Rmd file but could not find much information on the background. I assume you have not gotten around to this part. You made a good point in explaining why only data 25+ was used. From my understanding, I dont think you need to go into detail about the R coding specifics, like what the data was named in R, but maybe just touch on the packages used. 

 ### Summary assessment (PICK ONE, DELETE THE OTHERS)
 * very poor contextualization and motivation <- Let me know if I am looking at the right file!


 ## Question description
 How well and clear are the question(s)/hypotheses the project aims to address described? Is it clear how the questions relate to the data?

 ### Feedback and Comments
 I think your question is pretty clear, maybe put it into a question form. 

 ### Summary assessment
 * question/hypotheses fully clear


 ## Data description
 How well is the data overall described? Is the source provided? Is a codebook or other meta-information available that makes it clear what the data is? 

 ### Feedback and Comments
 This data set is pretty clear and straight forward. You could possibly go into detail on the variables included in the data set and how they are measured. 

 ### Summary assessment
 * source and overall structure of data somewhat explained


 ## Data wrangling and exploratory analysis
 How well is the data cleaned/processed and explored? Are all steps reasonable and well explained? Are alternatives discussed and considered? Are meaningful exploratory results shown (e.g. in the supplementary materials)?

 ### Feedback and Comments

 This is regarding the processing script called COVID.Rmd. I don't quite get why there is a threshold of 400 (my biostat understanding is still in the formation, I could just be nieve) but wouldn't you want all #s of covid deaths? I would also clean up the unneeded columns as well. I liked your plots for your exploratory model!
 Also, the GA file was not saving for me nor was it created in the code. Maybe it was accidentally deleted?

 ### Summary assessment
 * some weaknesses in wrangling and exploratory component



 ## Appropriateness of Analysis
 Were the analysis methods appropriate for the data? Was the analysis done properly? Were different components of the analysis (e.g. performance measure, variable selection, data pre-processing, model evaluation) done in the best way possible and explained well?

 ### Feedback and Comments

 I looked at Covid_Project.Rmd. I could not run this because the kableExtra package would not load for me, even after I installed the package. It could be my R version or some other computer issue on my end however
 -> error message Error: package or namespace load failed for ‘kableExtra’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
  there is no package called ‘systemfonts’

 I see there is a good bit of wrangling here, maybe it would be easier to move it to the COVID.Rmd doc? I like your # Assumption validation section, it really lays out everything you were talking about. You could c&p this into your manuscript

 ### Summary assessment
 * defensible but not optimal analysis 

 ## Presentation
 How well are results presented? Are tables and figures easy to read and understand? Are the main figures/tables publication level quality? 

 ### Feedback and Comments

 I think you have some great packages/code for all the diagnostic plots! Maybe some more visualization of just data other than histograms,I think a graph that stratify both covid and influenza and both deaths by age group would be a great way to see the data all at once. Your tree may have been messed up a bit, I think it counted all age groups as one decision but I could be wrong

 ### Summary assessment
 * results are presented ok, with room for improvement



 ## Discussion/Conclusions
 Are the study findings properly discussed? Are strengths and limitations acknowledged? Are findings interpreted properly?

 ### Feedback and Comments

 Not much here, but you have some comments in your script you could totally elaborate on!

 ### Summary assessment
 * major parts of discussion missing or wrong 


 ## Further comments





 # Overall project content evaluation
 Evaluate overall features of the project  by filling in the sections below.


 ## Structure
 Is the project well structured? Are files in well labeled folders? Do files have reasonable names? Are all "junk" files not needed for analysis/reproduction removed? By just looking at files and folders, can you get an idea of how things fit together?

 ### Feedback and Comments
 Yes, simple with the processing and COVID_Project.rmd script. I would delete all the other scripts you don't need

 ### Summary assessment
 * well structured


 ## Documentation 
 How well is the project documented? Are you able to understand each step of the whole analysis, each decision that was made, and each line of code? Is enough information provided as comments in code or as part of Rmd files? 

 ### Feedback and Comments

 You have some good comments sprinkled throughout and show a good understanding of diagnostic plots. Myabe add more about the mode you choose. I would explain each variable more as well

 ### Summary assessment
 * decently documented with some gaps




 ## Reproducibility
 Are all results fully reproducible? Is documentation provided which clearly explains how to reproduce things, and does it work without the need for any manual intervention? Are you able to re-run the whole analysis without having to do manual interventions/edits?

 ### Feedback and Comments

 For the most part, the only thing I had an issue with was the library(kableExtra) package


 ### Summary assessment
 * small parts not reproducible or required manual intervention 


 ## Thoroughness
 How thorough was the overall study? Were alternatives (e.g. different ways of processing the data or different models) considered? Were alternatives discussed? Were the questions/hypotheses fully and thoroughly addressed?

 ### Feedback and Comments

 I think this needs a bit of work. I am still not quite sure how you preprocessed the data

 ### Summary assessment
 * weak level of thoroughness



 ## Further comments

 I would start on condensing your preprocessing. It seems your analysis script does not use the data in your preprocessing script. Maybe include some more models? Or even more simple models similar to the one you did earlier. I would use a poission regression with count data. 

